README.rst

front page code snippet update

---

orbit/__init__.py
setup.py

for the `orbit.diagnostics.metrics.smape` change

small version nump

---

orbit/__init__.py
orbit/stan/lgt.stan
setup.py

taking max(x, 0) to avoid negative values; this is a temp fix for small negative margin that stop lgt in optimization.  later, we can improve by something more sophistcated.

minor fix on lgt

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

create issue template for `bug report` and `feature request`.
fix #242

Issue template

---

README.rst
docs/tutorials/dlt.ipynb
docs/tutorials/lgt.ipynb
docs/tutorials/pyro_basic.ipynb
docs/tutorials/quick_start.ipynb
examples/DLT_Example.ipynb
examples/Daily_Forecast_Example.ipynb
examples/LGT_Example.ipynb
examples/LGT_Pyro_Example.ipynb

update the readme, example notebooks, and tutorial notebooks for the change of percentile defaults in the plotting utility

Doc update

---

orbit/utils/dataset.py

create data loaders for example datasets: iclaims, m4, m5.
Fixes #227

data load wrappers

---

README.rst
docs/conf.py

add a button of `Edit on Github` on the landing pages of readthedocs.

add a button of "Edit on Github"

---

orbit/utils/features.py

Small enhancement of fft features to provide suffix and prefix of output columns

small update on fft utils

---

orbit/estimators/pyro_estimator.py

- make default total decay as 1.0 meaning no decay

small change on pyro-config

---

orbit/__init__.py
setup.py

small version bump

---

examples/KTR_Pyro_Example.ipynb
orbit/diagnostics/backtest.py

A general hyper-parameter tuning utility for orbit-typed models, with the help of the backtest modules in orbit.

Hyper tuning orbit

---

.travis.yml

Implement deployment through TravisCI conditional on version tagging
Fixes #290 
We will test by tagging a new version and pushing a new version release through PyPI

Setup TravisCI deployment for PyPI

---

.travis.yml

Debug pypi deployment in travis config
Will test in Travis CI console

Update travis config for pypi deployment

---

.travis.yml

use dpl v2 for travis config

---

orbit/models/dlt.py
orbit/models/ets.py
orbit/models/lgt.py

small fix to merge on dev-refactor-ets

Additional refinement on ETS Refactoring

---

orbit/models/ktr.py

trim `lev_knots_date` that are outside the training df

lev_knots_date trimming

---

tests/orbit/models/test_lgt.py

To address the issue of model reproducibility with a given seed, this PR adds a more strict unit test. No functionality is changed in the package as the results were already fully reproducible with a seed.
Adds a unit test to assert model training **and** model prediction is reproducible with a seed for `LGTFull`.
The test creates two instances of `LGTFull` and runs `fit()` and `predict()` for each instance.
Assertions check that every value of `LGTFull._posterior_samples` is identical in the two instances along with every value returned by `LGTFull.predict()`.
Unit test is parametrized for both `StanEstimatorMCMC` and `StanEstimatorVI`,  mixed regressor signs, and with seasonality values `1` and `52`

add unit tests to assert reproducibility of train and predict

---

RELEASE.md

Added documentation for release process for full release, quick release, and hotfix release
N/A

Documentation of release process in RELEASE.md

---

orbit/models/ktrlite.py
orbit/models/ktrx.py

allowing a scalar input to define a constant step of deriving knots

allow constant knot length

---

orbit/models/ktrx.py
orbit/pyro/ktrx.py

* make `._coef_prior_list` to be a deepcopy of `.coef_prior_list` 
* insert prior validation and filtering

Dev ktr new prior ingest

---

orbit/models/ktrlite.py
orbit/models/ktrx.py
orbit/pyro/ktr.py
orbit/pyro/ktrlite.py
orbit/pyro/ktrx.py

- added ktrlite.py for pyro
- enable validation in pyro sampling in both ktrlite and ktrx
- fix a few syntax with .to_event()
- fix a bug where default for input_prior should be [] not None

Feat ktr lite pyro

---

examples/Hyperparameter_Tuning_Example .ipynb
orbit/diagnostics/backtest.py

add a hyper-parameter tuning utility `orbit_grid_search` for orbit models

utility for hyper-parameter tuning

---

orbit/diagnostics/plot.py

Fixes # 306
1. make common inputs `title`, `figsize`, `fontsize` and `path` available to all  plot functions
2. provide suppressing plots input as `is_visible`

Organize Plotting functions and enhancement

---

orbit/diagnostics/plot.py

Revert "Organize Plotting functions and enhancement"

---

orbit/models/ktrx.py
orbit/pyro/ktrx.py

vectorize prior input from 1D (with for loop) to 2D
Makes KTR runs faster with prior import (slightly faster).
N/A

slightly tune performance of ktrx on speed

---

orbit/models/ktrx.py
orbit/pyro/ktrx.py

small enhance

---

docs/tutorials.rst
docs/tutorials/quick_start_DLT.ipynb
docs/tutorials/quick_start_LGT.ipynb
docs/tutorials/utilities_simulation.ipynb
examples/utilities_simulation.ipynb
orbit/utils/dataset.py

Fixes #334
- upload the enhanced iclaims dataset to master in this [commit](https://github.com/uber/orbit/commit/59d1206cf14278391e3889ca26aac6f04b7a959b)
-  change the URL back to master data file

fix data url in load_iclaims()

---

orbit/constants/constants.py
orbit/constants/dlt.py
orbit/constants/ets.py
orbit/constants/lgt.py
orbit/diagnostics/plot.py
orbit/estimators/base_estimator.py
orbit/estimators/pyro_estimator.py
orbit/initializer/dlt.py
orbit/initializer/ets.py
orbit/initializer/lgt.py
orbit/models/dlt.py
orbit/models/ets.py
orbit/models/lgt.py

Allow pickle write and load for orbit model object.
Fixes #340 Fixes #308
This is a bit hard to unit test but open to suggestion

Feat pickle fix

---

orbit/utils/kernels.py

we will use flat coefficients for future period instead of projected dynamic ones...

flat weights for out of sample time points

---

orbit/models/dlt.py
orbit/models/ets.py
orbit/models/lgt.py
orbit/stan/dlt.stan
orbit/stan/ets.stan
orbit/stan/lgt.stan
tests/orbit/models/test_dlt.py
tests/orbit/models/test_lgt.py

fix #157 
fix #188 
fix #346 
* unit test for fixed smoothing input and regression penalty: DLT model
* unit test for fixed smoothing input: LGT model
* `global_trend_option` and `regression_penalty` option check: DLT model

Dev unit test

---

orbit/utils/dataset.py

fix the logics of de-meaning in `load_iclaims()`

iclaims data de-meaning

---

requirements.txt

remove unused packages

---

docs/tutorials/ktrlite.ipynb
docs/tutorials/pyro_basic.ipynb

ktrlite tutorial cosmetics refinement

Tutorial refine

---

docs/conf.py
docs/index.rst
docs/requirements-docs.txt
docs/tutorials/pyro_basic.ipynb

highlight the code cell in notebook

---

docs/index.rst
docs/tutorials/build_your_own_model.ipynb
examples/build_your_own_model.ipynb
orbit/estimators/base_estimator.py
orbit/estimators/pyro_estimator.py
orbit/estimators/stan_estimator.py
orbit/models/template.py
orbit/utils/simulation.py

twist the estimator a bit to have a easier way to build your own model

tutorial of making your own model

---

docs/tutorials/build_your_own_model.ipynb
orbit/models/dlt.py
orbit/models/ets.py
orbit/models/ktrlite.py
orbit/models/lgt.py
orbit/models/template.py

Refine template further more where overriding `_set_dynamic_attributes()` is easier.

Refine Template - refine set dynamic attributes

---

orbit/diagnostics/plot.py

add in-sample line plot option

---

orbit/diagnostics/plot.py

linestyle option for both train and test period

linestyle option for both train and test period

---

orbit/models/template.py
orbit/utils/predictions.py

small improvement on errors raising on predictions utils usage

relabel and add assert statment

---

RELEASE.md
docs/tutorials/backtest.ipynb
docs/tutorials/build_your_own_model.ipynb
docs/tutorials/decompose_prediction.ipynb
docs/tutorials/dlt.ipynb
docs/tutorials/eda_function_demo.ipynb
docs/tutorials/ktrlite.ipynb
docs/tutorials/lgt.ipynb
docs/tutorials/model_diagnostics.ipynb
docs/tutorials/model_estimations.ipynb
docs/tutorials/pyro_basic.ipynb
docs/tutorials/quick_start.ipynb
docs/tutorials/regression.ipynb
orbit/__init__.py

* update the release guidance
* version bump
* apply the version bump to tutorial

Release v1.0.13

---

examples/hyper_parameters_tuning.ipynb
orbit/diagnostics/backtest.py
tests/orbit/models/test_dlt.py
tests/orbit/models/test_lgt.py

fix the bug in grid search tuning by using a more robust way to extract model signatures.
Fixes #436

more robust way to extract signatures of orbit models

---

orbit/estimators/base_estimator.py
orbit/estimators/pyro_estimator.py

Include a new hyper-parameter in `PyroVIEstimator` -- `init_scale`. It can enhances stability in high dimensional parameters and small dataset.  Also fixes #452

init scale for pyro-vi estimator

---

orbit/diagnostics/backtest.py
tests/orbit/diagnostics/test_backtest.py

allow for more flexible backtester inputs

---

orbit/models/dlt.py

Fix the way to calculate cauchy_sd. The old way will trigger a bug when the response values are all negative.
Fixes #458

fix cauchy_sd scalar

---

orbit/models/ktrx.py

A minor fix on defaults of ktrx and keep a lower bound of scale parameters

Keep a lower bound of scale parameters

---

orbit/models/template.py

if set to be False, the posterior samples will be discarded.

add a flag to keep posterior samples for aggregated template

---

orbit/models/dlt.py
orbit/models/lgt.py
orbit/models/template.py
tests/orbit/models/test_dlt.py
tests/orbit/models/test_lgt.py

Fix the bug that DLTMAP and LGTMAP fail for single regressor case.
Fixes #469 
unit test added for LGTMAP and DLTMAP

Fix single regressor bug

---

orbit/models/ktrlite.py

add an option for knot location either `mid_point` or `end_point` for ktrlite model.

option for end_point knot location

---

.github/workflows/python-test.yaml

Testing a solution of unit test with GA
Fixes #477 
Unit test with GA

Testing GA for Pytest

---

.github/workflows/pypi-deploy.yaml

Added a `.yaml` for PyPI deployment
Fixes #483 
Test the test with suggested template from GA

First test on GA for auto deployment on PyPI

---

.github/workflows/pypi-deploy.yaml
.github/workflows/python-test.yaml
orbit/estimators/stan_estimator.py
orbit/models/template.py
tests/orbit/models/test_ets.py

Just a merge to master for the GA workflows commits in dev.  should not impact model performance.

GA Workflow

---

orbit/forecaster/forecaster.py
orbit/forecaster/full_bayes.py
orbit/forecaster/map.py
orbit/forecaster/svi.py
orbit/models/ets.py
tests/orbit/models/test_ets.py

Temp work in fixing all unit tests on ETS

Dev rewrite v1.0.16 ets

---

examples/ets_example.ipynb
examples/ktrlite.ipynb
orbit/estimators/stan_estimator.py
orbit/forecaster/forecaster.py
orbit/stan/ktrlite.stan
orbit/template/ets.py
orbit/template/ktrlite.py
orbit/template/model_template.py

mainly ktr but some ets

---

orbit/estimators/pyro_estimator.py
orbit/estimators/stan_estimator.py

set proper verbose message for stan (map and mcmc) and pyro estimator.
fixes #452

Dev rewrite v1.0.16 estimator verbose

---

requirements.txt

relax the version requirement for matplotlib 
fixes #498

relax the version requirement for matplotlib

---

orbit/forecaster/forecaster.py
orbit/models/dlt.py
orbit/models/ets.py
orbit/models/ktr.py
orbit/models/ktrlite.py
orbit/template/dlt.py
orbit/template/ktr.py
orbit/template/ktrlite.py
orbit/template/lgt.py

a thorough cleanup of the docstrings for the rewriting branch

docstrings

---

docs/tutorials/ktr1.ipynb
docs/tutorials/ktr2.ipynb
docs/tutorials/ktr3.ipynb
docs/tutorials/ktr4.ipynb

This is an update to the text in the tutorial notebooks. 

Dev rewrite v1.0.16 gavin edits round3

---

tests/orbit/diagnostics/test_backtest.py

add the unit test for backtester

unit test for backtester

---

docs/tutorials/build_your_own_model.ipynb
docs/tutorials/decompose_prediction.ipynb
docs/tutorials/dlt.ipynb
docs/tutorials/exploratory_data_analysis.ipynb
docs/tutorials/ktr1.ipynb
docs/tutorials/ktr2.ipynb
docs/tutorials/ktr3.ipynb
docs/tutorials/ktr4.ipynb
docs/tutorials/lgt.ipynb
docs/tutorials/model_estimations.ipynb
docs/tutorials/pyro_basic.ipynb
docs/tutorials/quick_start.ipynb
docs/tutorials/regression.ipynb

refresh some tutorials to reflect the version as `v1.1.0dev`

tutorial printing version update

---

orbit/template/ktrlite.py

fix palette in ktrlite

---

orbit/stan/lgt.stan

fix a bug in the bound of negative coefficient prior in the stan code

correct negative coef bound bug

---

examples/waic_exploratory.ipynb
examples/wbic_exploratory.ipynb

Update notebook to reflect exploratory of WBIC / WAIC
Fixes #631
Notebook can be found [here](https://nbviewer.org/github/uber/orbit/blob/eaa942d72bfd59796c428514aaa804c8bf6d2f8c/examples/WBIC%20stan%20Gen%20LM%2C%20LM%2C%20AR%202021-11-20.ipynb)

Update notebook to reflect exploratory of WBIC / WAIC

---

orbit/forecaster/full_bayes.py
orbit/forecaster/map.py
orbit/forecaster/svi.py
tests/orbit/models/test_dlt.py
tests/orbit/models/test_ets.py
tests/orbit/models/test_lgt.py

add seed option in predict mode
fixes #646

Dev seed predict

---

docs/tutorials/ets_lgt_dlt_missing_response.ipynb

cosmetics fix in missing value tutorial

tutorial fix

---

README.md
docs/changelog.rst

* add change log for v1.1
* readme file update to add slack channel

Changelog v1.1

---

orbit/utils/plot.py

Introduce try and except block when exception caught in introducing orbit plot style.
Fixes #671 

Bug fix/plot style

---

README.md

The readme file was updated to incorporate the conda install instruction.
This PR is representative of the conda-forge PR that added `orbit-ml` to conda-forge channel. The details of which are available in the issue #674.
Fixes #674  (issue)
The conda-forge PR: https://github.com/conda-forge/staged-recipes/pull/17563

Added conda install information

---

orbit/diagnostics/plot.py
tests/orbit/diagnostics/test_plot.py

Dev plt enhance

---

orbit/estimators/stan_estimator.py
orbit/utils/params_tuning.py

at this point, no more print statements after a compressive check.
fixes #723 
fixes #694

Dev better logging

---

.github/workflows/black.yaml

Outputting code diff for lint build

adding diff output of black run

---

CONTRIBUTING.md
examples/dlt_daily_forecast.ipynb
examples/hyper_parameters_tuning.ipynb
orbit/diagnostics/plot.py
orbit/utils/knots.py
orbit/utils/params_tuning.py
orbit/utils/simulation.py
tests/orbit/models/test_dlt.py
tests/orbit/models/test_lgt.py
tests/orbit/utils/params_tuning.py

Refactor param tuning

---

docs/tutorials/backtest.ipynb
docs/tutorials/decompose_prediction.ipynb
docs/tutorials/ets_lgt_dlt_missing_response.ipynb
docs/tutorials/ktr2.ipynb
docs/tutorials/lgt.ipynb
docs/tutorials/model_estimations_predictions.ipynb
docs/tutorials/regression_penalty.ipynb
docs/tutorials/regression_prior.ipynb
docs/tutorials/utilities_simulation.ipynb
docs/tutorials/wbic.ipynb

correct the typos here and there in the tutorials

typo fixes

---

RELEASE.md
requirements.txt

* update torch version requirement to dodge the potential import error
* update the release.md

Dev requirements fix

---

.github/workflows/build.yaml
requirements.txt

Removing python 3.9 build for now.  There is some changes need to fix in the numpy.distutils in pystan2.19 installaion.

Bug fix/numpy freeze

---

.github/workflows/black.yaml
.github/workflows/build.yaml
docs/changelog.rst
orbit/__init__.py
requirements.txt

Hot Fix on requirement.txt problem; Pushed for v1.1.4.1

Hot Fix on requirement.txt problem; Pushed for v1.1.4.1

---

requirements.txt
setup.py

Stan prune 20240111

---

.github/workflows/pypi-deploy.yaml

adding auditwheel to repair platform specific linux wheel

---

docs/changelog.rst

[adding auditwheel to repair platform specific linux wheel](https://github.com/uber/orbit/commit/b36fbfdbde2de63c59f2f707f3c906ccc18575de)

Use Aduditwheel for platform specific linux wheel

---

.github/workflows/pypi-deploy.yaml

fix typo and add step to remove the linux wheel

---

.github/workflows/pypi-deploy.yaml

change the platform to manylinux2014

---

.github/workflows/pypi-deploy.yaml

Clean up workflow, add step to keep only stan file in orbit/stan

Update pypi-deploy workflow to sdist

---

.github/workflows/pypi-deploy.yaml

Retry pip install ., attempt to resolve conda build issue

Retry pip install .
